FantacyRecipe/Models/Recipe.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FantacyRecipe.Models
{
  public class Recipe
  {
    public int RecipeId { get; set; }
    [Required(ErrorMessage = "The Recipe Name is the most important information!")]
    public string RecipeName { get; set; }
    public string RecipeIngredient { get; set; }
    public string RecipeInstructions {get;set;}

    [Required(ErrorMessage = "The Recipe Rate is required!")]
    public string RecipeRate { get; set; }

    public List<RecipeTag> JoinEntities { get; set; }

    public ApplicationUser User { get; set; } 
  }
}

FantacyRecipe/Controllers/RecipesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using FantacyRecipe.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace FantacyRecipe.Controllers
{
  [Authorize]

  public class RecipesController : Controller
  {
    private readonly FantacyRecipeContext _db;

    private readonly UserManager<ApplicationUser> _userManager;

    public RecipesController(UserManager<ApplicationUser> userManager, FantacyRecipeContext db)
    {
      _userManager = userManager;

      _db = db;
    }
    
    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Recipe> allRecipes = _db.Recipes
      .OrderBy(recipe => recipe.RecipeRate).ToList();                            
      return View(allRecipes);
    }

    public async Task<ActionResult> MyRecipes()
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      List<Recipe> userRecipes = _db.Recipes
      .Where(entry => entry.User.Id == currentUser.Id)
      .OrderBy(recipe => recipe.RecipeRate).ToList();                            
      return View(userRecipes);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Recipe recipe)
    {
      if (!ModelState.IsValid)
      {
        return View(recipe);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        recipe.User = currentUser;

        _db.Recipes.Add(recipe);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      
    }
   
    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      Recipe thisRecipe = _db.Recipes
                             .Include(recipe => recipe.JoinEntities)
                             .ThenInclude(join => join.Tag)
                             .FirstOrDefault(recipe => recipe.RecipeId == id);
      return View(thisRecipe);
    }

    public async Task<ActionResult> Edit(int id)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      Recipe thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
      if (thisRecipe.User == currentUser)
      {
        return View(thisRecipe);
      }
      else
      {
        return RedirectToAction("Index");
      }
    }

    [HttpPost]
    public ActionResult Edit(Recipe recipe)
    {
      _db.Recipes.Update(recipe);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public async Task<ActionResult> Delete(int id)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      Recipe thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
      if (thisRecipe.User == currentUser)
      {
        return View(thisRecipe);
      }
      else
      {
        return RedirectToAction("Index");
      }
      
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Recipe thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
      _db.Recipes.Remove(thisRecipe);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public async Task<ActionResult> AddTag(int id)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      List<Tag> userTags = _db.Tags
                                .Where(entry =>entry.User.Id == currentUser.Id)
                                .OrderBy(tag => tag.TagName)
                                .ToList();

      Recipe thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
      
      ViewBag.TagId = new SelectList(userTags, "TagId", "TagName");
      
      return View(thisRecipe);
    }

    [HttpPost]
    public ActionResult AddTag(Recipe recipe, int tagId)
    {
      #nullable enable
      RecipeTag? joinEntity = _db.RecipeTags.FirstOrDefault(join => (join.TagId == tagId && join.RecipeId == recipe.RecipeId));
      #nullable disable

      if (joinEntity == null && tagId != 0)
      {
        _db.RecipeTags.Add(new RecipeTag() { TagId = tagId, RecipeId = recipe.RecipeId });
        _db.SaveChanges();
      }

      return RedirectToAction("Details", new { id = recipe.RecipeId });
    }  

    [HttpPost]
    public async Task<ActionResult> DeleteJoin(int joinId)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      RecipeTag joinEntry = _db.RecipeTags.FirstOrDefault(entry => entry.RecipeTagId == joinId);
      Recipe thisRecipe = _db.Recipes.FirstOrDefault(entry => entry.RecipeId == joinEntry.RecipeId);
      if (thisRecipe.User == currentUser)
      {
        _db.RecipeTags.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      else
      {
        return RedirectToAction("Index", "Home");
      }
    }

    public ActionResult Search()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Search(Recipe input)
    {
//  List<Recipe> model = _db.Recipes.Where(recipe => recipe.Contains(recipe.Re == input.RecipeIngredient)).ToList();                                  

      string inputString = input.RecipeIngredient;
      List<Recipe> recipeList = _db.Recipes
                                  .Where(recipe => recipe.RecipeIngredient
                                  .Contains(inputString))
                                  .ToList();    
      
      if (recipeList.Count != 0)
      {
        return RedirectToAction("Result", recipeList);
      }
      
      else
      {
        return RedirectToAction("NoResult");
      }
      
    }

    public ActionResult NoResult()
    {
      return View();
    }

    public ActionResult Result(List<Recipe> recipeList)
    {
      return View(recipeList);
    }
    
  }
}
 

FantacyRecipe/Controllers/TagsController.cs
using Microsoft.AspNetCore.Mvc;
using FantacyRecipe.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace FantacyRecipe.Controllers
{
  [Authorize]

  public class TagsController : Controller
  {
    private readonly FantacyRecipeContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TagsController(UserManager<ApplicationUser> userManager, FantacyRecipeContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    
    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Tag> myTags = _db.Tags
                            .OrderBy(tag => tag.TagName)
                            .ToList();
      return View(myTags);
    }

    public async Task<ActionResult> MyTags()
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      List<Tag> userTags = _db.Tags
                                .Where(entry =>entry.User.Id == currentUser.Id)
                                .OrderBy(tag => tag.TagName)
                                .ToList();
      return View(userTags);
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      Tag thisTag = _db.Tags
          .Include(tag => tag.JoinEntities)
          .ThenInclude(join => join.Recipe)
          .FirstOrDefault(tag => tag.TagId == id);
      return View(thisTag);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Tag tag)
    {
      if (!ModelState.IsValid)
      {
        return View(tag);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        tag.User = currentUser;

        _db.Tags.Add(tag);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }

    }
    
    public async Task<ActionResult> AddRecipe(int id)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      List<Recipe> userRecipes = _db.Recipes
                                .Where(e => e.User.Id == currentUser.Id)
                                .OrderBy(recipe => recipe.RecipeRate)
                                .ToList();
                                
      Tag thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      ViewBag.RecipeId = new SelectList(userRecipes, "RecipeId", "RecipeName");
      return View(thisTag);
    }

    [HttpPost]
    public ActionResult AddRecipe(Tag tag, int recipeId)
    {
      #nullable enable
      RecipeTag? joinEntity = _db.RecipeTags.FirstOrDefault(join => (join.RecipeId == recipeId && join.TagId == tag.TagId));
      #nullable disable
      
      if (joinEntity == null && recipeId != 0)
      {
        _db.RecipeTags.Add(new RecipeTag() { RecipeId = recipeId, TagId = tag.TagId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = tag.TagId });
    }

    public async Task<ActionResult> Edit(int id)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      Tag thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      if (thisTag.User == currentUser)
      {
        return View(thisTag);
      }
      else 
      {
        return RedirectToAction("Index");
      }
    }

    [HttpPost]
    public ActionResult Edit(Tag tag)
    {
      _db.Tags.Update(tag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public async Task<ActionResult> Delete(int id)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      Tag thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      if (thisTag.User == currentUser)
      {
        return View(thisTag);
      }
      else 
      {
        return RedirectToAction("Index");
      }
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Tag thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      
      _db.Tags.Remove(thisTag);
      _db.SaveChanges();
      return RedirectToAction("Index");

    }

    [HttpPost]
    public async Task<ActionResult> DeleteJoin(int joinId)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      RecipeTag joinEntry = _db.RecipeTags.FirstOrDefault(entry => entry.RecipeTagId == joinId);
      Tag thisTag = _db.Tags.FirstOrDefault(entry => entry.TagId == joinEntry.TagId);
      if (thisTag.User == currentUser)
      {
        _db.RecipeTags.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      else
      {
        return RedirectToAction("Index", "Home");
      }
    }
    
  }
}

FantacyRecipe/Views/Recipes/AddTag.cshtml
@{
  Layout = "_Layout";
}

@model FantacyRecipe.Models.Recipe

<h2>Add a tag</h2>

<h4>Add a tag to this recipe: @Html.DisplayFor(model => model.RecipeName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.RecipeId)

    @Html.Label("Select tag")
    @Html.DropDownList("TagId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

FantacyRecipe/Views/Recipes/Create.cshtml
@{
  Layout = "_Layout";
}

@model FantacyRecipe.Models.Recipe

<h4>Add a new recipe</h4>

<p>@Html.ValidationMessageFor(m=>m.RecipeName,"", new {@class = "text-danger", @style = "font-weight: 600;"})</p>
<p>@Html.ValidationMessageFor(m=>m.RecipeRate,"", new {@class = "text-danger", @style = "font-weight: 600;"})</p>

@using (Html.BeginForm())
{
  <p>Recipe Name: @Html.TextBoxFor(model => model.RecipeName)</p>
  <p>Recipe Rating: @Html.TextBoxFor(model => model.RecipeRate)</p>
  <p>Recipe Ingredients: @Html.TextBoxFor(model => model.RecipeIngredient)</p>
  <p>Recipe Instructions:</p>
  <p>@Html.TextBoxFor(model => model.RecipeInstructions)</p>

  <input type="submit" value="Add new recipe" class="btn btn-default" />
}

<p>@Html.ActionLink("Show all recipes", "Index")</p>

FantacyRecipe/Views/Recipes/Delete.cshtml
@{
  Layout = "_Layout";
}

@model FantacyRecipe.Models.Recipe

<h2>Are you sure you want to delete this recipe?</h2>

@Html.DisplayNameFor(model => model.RecipeName): @Html.DisplayFor(model => model.RecipeName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

FantacyRecipe/Views/Recipes/Details.cshtml
@{
  Layout = "_Layout";
}

@using FantacyRecipe.Models
@model FantacyRecipe.Models.Recipe

<h2>Recipe Details</h2>
<hr />
<h3>Recipe Name: @Html.DisplayFor(model => model.RecipeName)</h3>

<p>Recipe Rating: @Html.DisplayFor(model => model.RecipeRate)</p>
<p>Ingredients: @Html.DisplayFor(model => model.RecipeIngredient)</p>
<p>Instructions: @Html.DisplayFor(model => model.RecipeInstructions)</p>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This recipe does not have any tags.</p>
}
else
{
  <h4>Tags the recipe has:</h4>
  <ul>
  @foreach(RecipeTag join in Model.JoinEntities)
  {
    <li>@join.Tag.TagName</li>

    @using (Html.BeginForm("DeleteJoin", "Recipes"))
    {
      @Html.Hidden("joinId", @join.RecipeTagId)
      @if (User.Identity.IsAuthenticated)
      {
        <input type="submit" value="Remove"/>
      }
    }
    
  }
  </ul>
}

<p>@Html.ActionLink("Back to list", "Index")</p>

<p>@Html.ActionLink("Add a Tag", "AddTag", new { id = Model.RecipeId })</p>

<p>@Html.ActionLink("Edit Recipe", "Edit", new { id = Model.RecipeId })</p>

<p>@Html.ActionLink("Delete Recipe", "Delete", new { id = Model.RecipeId })</p>

FantacyRecipe/Views/Recipes/Edit.cshtml
@{
  Layout = "_Layout";
}

@model FantacyRecipe.Models.Recipe

<h4>Edit this Recipe: @Html.DisplayFor(m=>m.RecipeName)</h4>

<p>@Html.ValidationMessageFor(m=>m.RecipeName,"", new {@class = "text-danger", @style = "font-weight: 600;"})</p>

@using (Html.BeginForm())
{
  @Html.HiddenFor(m => m.RecipeId)

  <p>Recipe Name: @Html.EditorFor(model => model.RecipeName)</p>
  <p>Recipe Rating: @Html.EditorFor(model => model.RecipeRate)</p>
  <p>Recipe Ingredients: @Html.EditorFor(model => model.RecipeIngredient)</p>
  <p>Recipe Instructions:</p>
  <p>@Html.EditorFor(model => model.RecipeInstructions)</p>
  
  <input type="submit" value="Save Changes" class="btn btn-default" />
}

<p>@Html.ActionLink("Back to recipes","Index")<p>

FantacyRecipe/Views/Recipes/Index.cshtml
@{
  Layout = "_Layout";
}

@using FantacyRecipe.Models;

<h1>Recipes</h1>

@if (@Model.Count == 0)
{
  <h3>No recipes have been added yet!</h3>
} 

<ul>
  @foreach(Recipe recipe in Model)
  {
    <li>@Html.ActionLink($"{recipe.RecipeName}", "Details", new { id = recipe.RecipeId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new recipe", "Create")</p>
<p>@Html.ActionLink("Create a Tag", "Create", "Tags")</p>

@if (User.Identity.IsAuthenticated)
{
  <p>Hello @User.Identity.Name!</p>
  
  <p>@Html.ActionLink("View my recipes", "MyRecipes")</p>
}

FantacyRecipe/Views/Recipes/MyRecipes.cshtml
@{
  Layout = "_Layout";
}

@using FantacyRecipe.Models;

<h1>@User.Identity.Name's Recipes</h1>

@if (@Model.Count == 0)
{
  <h3>No recipes have been added yet!</h3>
} 

<ul>
  @foreach(Recipe recipe in Model)
  {
    <li>@Html.ActionLink($"{recipe.RecipeName}", "Details", new { id = recipe.RecipeId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new recipe", "Create")</p>
<p>@Html.ActionLink("Create a Tag", "Create", "Tags")</p>
<p>@Html.ActionLink("Recipes Index", "Index", "Recipes")</p>

FantacyRecipe/Views/Recipes/NoResult.cshtml
@{
  Layout = "_Layout";
}

<h3>No Recipe Found</h3>

<p>@Html.ActionLink("Back to list", "Index")</p>

FantacyRecipe/Views/Recipes/Result.cshtml
@{
  Layout = "_Layout";
}

@using FantacyRecipe.Models;
@*@model List<Recipe>;*@

<h2>Searched Results</h2>
<p>@Model.Count is this thing on</p>

 <p>recipeList</p>
<ul>
  @foreach(Recipe recipe in Model)
  {
    <li>Recipe: @Html.ActionLink($"{recipe.RecipeName}", "Details", new { id = recipe.RecipeId })</li>
  }
</ul>

FantacyRecipe/Views/Recipes/Search.cshtml
@{
  Layout = "_Layout";
}

@model FantacyRecipe.Models.Recipe

<h4>Search a recipe by Ingredient.</h4>

@using (Html.BeginForm())
{

  <p>Recipe Ingredients: @Html.TextBoxFor(model => model.RecipeIngredient)</p>

  <input type="submit" value="Search a recipe" class="btn btn-default" />
}

<p>@Html.ActionLink("Show all recipes", "Index")</p>